### ISSUE TITLE
Change authentication in OpenCommandChannel

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/cms-sdk-net#4]
Smartling context service is going to change authentication endpoint. Before it expected `projectId` and `apiKey`, new one will expect `projectId` and `accessToken`.

**DoD**:
Change required properties of `CmsSdkClient` and `OpenCommandChannel()`

**Comment by dotnetrocks** [comment]
>Smartling context service is going to change authentication endpoint
Is the task ready for work?

**Comment by dimitrystd** [comment]
The new context service is almost there. I hope to see it on stg\prod by the end of this week.

**Comment by dimitrystd** [comment]
It was decided to add one more parameter {{tokenType}}. Thus `open command` will look like
```
wss://cms.smartling.com/command/websocket?projectId=1295c174d&tokenType=Bearer&accessToken=eyJhbGciOiJSUzI1NiJ9......
```

**Comment by dotnetrocks** [comment]
Is it released already? Can I test it with production services?

**Comment by dotnetrocks** [comment]
Done & uploaded to Nuget as 2.0.0
