### ISSUE TITLE
Remove key parameter from Upload Command

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/cms-sdk-net#5]
_Related to #4_
**This task is still in draft state**
The current upload command looks like
```
POST https://cms.smartling.com/upload?{parameters}
```
name | meaning | notes
------------ | ------------- | -------------
key | API key | This API requires a valid key.
projectId | Project ID | Identifier of your project.
rid | Request ID | The ID of the original request obtained from the command channel

It looks like we can remove `key` from request because we already have unique `rid` with short TTL (about 20sec)

**Comment by dotnetrocks** [comment]
Done.
